import { prisma } from './lib/prisma';

async function seed() {
  console.log('🌱 Seeding database...');

  await prisma.internship.deleteMany();

  await prisma.internship.createMany({
    data: [
      {
        title: 'Software Development Intern',
        company: 'DRDO',
        source: 'drdo.gov.in',
        type: 'GOVERNMENT',
        domain: ['Software', 'Defence'],
        location: 'Delhi',
        isRemote: false,
        stipendMin: 10000,
        stipendMax: 15000,
        duration: '2 months',
        deadline: new Date('2025-07-31'),
        applyUrl: 'https://drdo.gov.in',
        status: 'OPEN',
        verified: true,
        skillsReq: ['C++', 'Python', 'Linux'],
        criteria: 'B.Tech CSE/ECE, 3rd or 4th year',
        description: 'Work on defence software systems with the DRDO research team in Delhi.',
      },
      {
        title: 'Full Stack Developer Intern',
        company: 'Razorpay',
        source: 'razorpay.com',
        type: 'STARTUP',
        domain: ['Web Development', 'FinTech'],
        location: 'Bangalore',
        isRemote: true,
        stipendMin: 25000,
        stipendMax: 40000,
        duration: '3 months',
        deadline: new Date('2025-08-15'),
        applyUrl: 'https://razorpay.com/jobs',
        status: 'OPEN',
        verified: true,
        skillsReq: ['React', 'Node.js', 'TypeScript', 'PostgreSQL'],
        criteria: 'B.Tech CSE, 3rd year and above',
        description: 'Build and ship features for Razorpay payment infrastructure used by millions.',
      },
      {
        title: 'Cybersecurity Analyst Intern',
        company: 'CERT-In',
        source: 'cert-in.org.in',
        type: 'GOVERNMENT',
        domain: ['Cybersecurity', 'Networking'],
        location: 'Delhi',
        isRemote: false,
        stipendMin: 12000,
        stipendMax: 18000,
        duration: '2 months',
        deadline: new Date('2025-07-20'),
        applyUrl: 'https://cert-in.org.in',
        status: 'OPEN',
        verified: true,
        skillsReq: ['Networking', 'Linux', 'Python', 'Security+'],
        criteria: 'B.Tech CSE/IT, 2nd year and above',
        description: 'Work with India\'s national cybersecurity agency on threat analysis and incident response.',
      },
      {
        title: 'React Frontend Intern',
        company: 'Zepto',
        source: 'zeptonow.com',
        type: 'STARTUP',
        domain: ['Frontend', 'Web Development'],
        location: 'Mumbai',
        isRemote: true,
        stipendMin: 20000,
        stipendMax: 35000,
        duration: '3 months',
        deadline: new Date('2025-08-30'),
        applyUrl: 'https://zeptonow.com/careers',
        status: 'OPEN',
        verified: false,
        skillsReq: ['React', 'TypeScript', 'Tailwind CSS'],
        criteria: 'Any year, strong React portfolio required',
        description: 'Work on Zepto\'s consumer-facing web app serving 10M+ users across India.',
      },
      {
        title: 'ML Research Intern',
        company: 'ISRO',
        source: 'isro.gov.in',
        type: 'GOVERNMENT',
        domain: ['Machine Learning', 'Research', 'Space'],
        location: 'Bangalore',
        isRemote: false,
        stipendMin: 15000,
        stipendMax: 20000,
        duration: '2 months',
        deadline: new Date('2025-07-10'),
        applyUrl: 'https://isro.gov.in',
        status: 'OPEN',
        verified: true,
        skillsReq: ['Python', 'TensorFlow', 'Data Analysis'],
        criteria: 'B.Tech CSE/EE, CGPA 8.0+',
        description: 'Apply ML techniques to satellite imagery analysis at ISRO\'s Space Applications Centre.',
      },
      {
        title: 'Backend Engineer Intern',
        company: 'CRED',
        source: 'cred.club',
        type: 'STARTUP',
        domain: ['Backend', 'FinTech'],
        location: 'Bangalore',
        isRemote: true,
        stipendMin: 30000,
        stipendMax: 50000,
        duration: '3 months',
        deadline: new Date('2025-09-01'),
        applyUrl: 'https://cred.club/careers',
        status: 'OPEN',
        verified: false,
        skillsReq: ['Node.js', 'PostgreSQL', 'Redis', 'TypeScript'],
        criteria: 'B.Tech CSE, 3rd/4th year',
        description: 'Build backend APIs for CRED\'s credit card management platform.',
      },
      {
        title: 'Data Science Intern',
        company: 'NASSCOM',
        source: 'nasscom.in',
        type: 'CORPORATE',
        domain: ['Data Science', 'Analytics'],
        location: 'Hyderabad',
        isRemote: true,
        stipendMin: 18000,
        stipendMax: 25000,
        duration: '2 months',
        deadline: new Date('2025-08-01'),
        applyUrl: 'https://nasscom.in',
        status: 'OPEN',
        verified: true,
        skillsReq: ['Python', 'Pandas', 'SQL', 'Tableau'],
        criteria: 'Any engineering branch, 2nd year+',
        description: 'Analyse India\'s IT industry data and build dashboards for policy research.',
      },
      {
        title: 'iOS Developer Intern',
        company: 'Swiggy',
        source: 'swiggy.com',
        type: 'CORPORATE',
        domain: ['Mobile', 'iOS'],
        location: 'Bangalore',
        isRemote: false,
        stipendMin: 35000,
        stipendMax: 50000,
        duration: '3 months',
        deadline: new Date('2025-08-20'),
        applyUrl: 'https://swiggy.com/careers',
        status: 'OPEN',
        verified: false,
        skillsReq: ['Swift', 'Xcode', 'UIKit', 'REST APIs'],
        criteria: 'B.Tech CSE, 3rd year preferred',
        description: 'Build features for Swiggy\'s iOS app used by 5M+ daily active users.',
      },
    ],
  });

  console.log('✅ Seeded 8 internships');
  await prisma.$disconnect();
}

seed().catch(console.error);